### ISSUE TITLE
Appreciation for CountGD and Query on Bounding Box Accuracy

### ISSUE THREAD

**Issue by chwang589** [niki-amini-naieni/CountGD#14]
Hello @niki-amini-naieni,

Firstly, I wanted to express my admiration for the work you've done on the CountGD project. It's impressive how you've managed to develop a tool that aids in object counting with such precision.

However, I've encountered a slight issue that I believe needs your attention. While using CountGD, I've noticed that the bounding boxes generated around the objects are not always perfectly accurate. Sometimes they either slightly miss the edges of the objects or encompass more area than necessary.

Could you please provide some insight into this issue? Is it a common problem that other users have reported, or is it specific to my setup? I would appreciate any guidance on how to improve the bounding box accuracy or if there are any upcoming updates that address this.

I've attached a few screenshots to illustrate the issue. Looking forward to your response.

Best regards,

![image](https://github.com/user-attachments/assets/667023a9-e946-4d7e-aa47-a2fa9126e694)
![image](https://github.com/user-attachments/assets/9043495c-89cb-4ee0-8f8b-8e66de4ea922)

**Comment by niki-amini-naieni** [comment]
Dear @chwang589, thank you for your question. CountGD was trained to output *center points*, not bounding boxes, as it is a counting model not an object detector. Therefore, the bounding boxes CountGD outputs may not be as accurate as those of object detectors, as CountGD was not trained for this task. If you look at the loss for CountGD, it uses the *center points* not the bounding box coordinates for training. This is because counting data in the standard FSC-147 benchmark provides only the approximate object centers rather than bounding box coordinates for training. I have pasted relevant part of the paper below. 

<img width="650" alt="image" src="https://github.com/user-attachments/assets/a678b874-819d-4f8d-b6d8-ae847904e79b">

**Comment by chwang589** [comment]
thanks for your reply
