### ISSUE TITLE
Text Input clarification

### ISSUE THREAD

**Issue by udit01** [niki-amini-naieni/CountGD#4]
Hello, Great work by the authors, I am locally using it on my custom datasets. 
I am using the app.py and config code to do 1 image inference at a time which I recommend putting on github for convenience as someone else asked for an API.
I had a few questions: 
1. In your experience is it better to use the text input as : 'blueberry' or 'blueberries'  , 'bottle' or 'bottles' ? because I'm trying and it gives different results for slightly different images (same count of objects, but from a different angle) depending on the different keyword text input. Is there a way to reliably tell? 
2. Is it better to use 'item' / 'objects' / 'everything' VS "item and fruits and bottles and everything" as keyword (just and (or or) all the words) . I thought the first would be enough, but in most cases, the AND union gives MORE count(not necessarily  correct) compared to OR union vs just 'everything '/'item' . But in some cases 'item' detected more items than 'item and apple and ... ' . What are you thoughts about that . 
3. What if I want to detect ALL the objects in an image... how can I go about doing that? what's the best way according to you?
4. Is it possible to have a specific object in image_A and then count the instances of THAT object in image_B?  (using image instead of 'word' per see) 
Any resources you have on these questions will be super helpful!
(I'm not using exemplars in any of these)
(I am also aware, that your model is very good when given exemplars and best & correct prompts, but my use-cases were slightly different, with requiring no human intervention)

Thanks for making this model available!

**Comment by niki-amini-naieni** [comment]
Hi @udit01, thank you for your questions! I have responded to the issue about 1 image inference (it was closed by the person who opened it). There is already an online Hugging Face app I created (with an available docker image that you can run locally) that allows you to do 1 image inference. For more details, see my follow-up to the issue you mentioned [here](https://github.com/niki-amini-naieni/CountGD/issues/2) or directly try the app yourself [here](https://huggingface.co/spaces/nikigoli/countgd).

RE: Question 1
I tested the model on singular forms of different words, so 'blueberry' instead of 'blueberries.' This is also the format I used when training the CountGD model, so I would use the singular forms for more reliable results. Below is a simple test for 'blueberry' using the app. However, I have not done extensive tests to see if the plural versions are always worse. 

Using 'blueberry':
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/aa18fa09-c63c-4c37-aaa0-0348fde58ea6">

Using 'blueberry' + 2 visual exemplars:
![image](https://github.com/user-attachments/assets/0553359f-5606-4de2-8dc5-4920c88ff067)

Using 'blueberries':
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/4136fbb2-3985-477a-beea-763ae8e777b0">

**Comment by udit01** [comment]
Hello @niki-amini-naieni . Thank you for taking the time to respond to all of my queries. 
Your answers to each one is exactly what I needed and more. Thank you for explaining all the nuances in depth and so clearly~!
All the best for the training script. I am looking forward to it!!
